Repository kokkos/pykokkos, pull requests merged in 2022-09, with the labels that each got.

#77 ENH: add int8/uint8
  pykokkos/core/cppast/decl.py
  pykokkos/core/visitors/visitors_util.py
  pykokkos/interface/__init__.py
  pykokkos/interface/data_types.py
  pykokkos/interface/views.py
Labels: enhancement, Python Array API Standard

#75 CI: simplify pybind11
  .github/workflows/main_ci.yml
Labels: continuous integration

#76 Added Multiple basic ufuncs
  pykokkos/__init__.py
  pykokkos/lib/ufuncs.py
  tests/test_ufuncs.py
Labels: ufuncs

#82 ENH: add API constants
  .github/workflows/array_api.yml
  .github/workflows/main_ci.yml
  pykokkos/__init__.py
  pykokkos/interface/views.py
  pykokkos/lib/constants.py
  pykokkos/lib/ufuncs.py
  setup.py
  tests/test_views.py
Labels: Python Array API Standard

#87 BUG: uint32/64 wrapping
  pykokkos/interface/views.py
  tests/test_views.py
Labels: bug

#88 MAINT, BUG: typing cleanups
  pykokkos/interface/data_types.py
  pykokkos/interface/views.py
Labels: bug, maintenance

#73 ENH: pk.ones() to API standard
  .github/workflows/array_api.yml
  pykokkos/__init__.py
  pykokkos/interface/views.py
  pykokkos/lib/create.py
  pykokkos/lib/ufuncs.py
  pykokkos/lib/util.py
Labels: enhancement, Python Array API Standard

#89 TST, MAINT: test durations
  runtests.py
Labels: testing, maintenance

#81 ENH: changes needed to pass `array_api_tests/test_creation_functions.py::test_ones_like`
  .github/workflows/array_api.yml
  pykokkos/__init__.py
  pykokkos/lib/create.py
  pykokkos/lib/info.py
  pykokkos/lib/manipulate.py
  pykokkos/lib/ufuncs.py
Labels: enhancement, Python Array API Standard

#90 ENH: support result_type
  .github/workflows/array_api.yml
  pykokkos/interface/__init__.py
  pykokkos/interface/views.py
  tests/test_views.py
Labels: enhancement, Python Array API Standard

#92 ENH: log10 to API standard
  .github/workflows/array_api.yml
  pykokkos/interface/views.py
  pykokkos/lib/ufuncs.py
Labels: Python Array API Standard, ufuncs

#99 CI: pin hypothesis
  .github/workflows/array_api.yml
Labels: continuous integration

#98 WIP, MAINT: pre-compile ufuncs
  .github/workflows/array_api.yml
  pre_compile_tools/pre_compile_ufuncs.py
  pykokkos/lib/ufuncs.py
Labels: testing, maintenance

#96 MAINT, CI: Python 3.11 rc2
  .github/workflows/main_ci.yml
Labels: maintenance, continuous integration
